baseURL: "https://k2tuitaalias.github.io/"
languageCode: "en-us"
title: "Kätu in Italia"
theme: "puppet"

copyright: ""
paginate: 3
languageCode: "en"
defaultContentLanguage: "en"
useFaviconGenerator: true

params:
  img_home: "img/home-bg.jpg"
  img_404: "img/404-bg.jpg"
  sidebar:
    enable: false